image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: "build"
  script:
    - rm ./package-lock.json
    - npm install --quiet
    - npm i -g firebase-tools
    - npm run build-prod
  artifacts:
    when: on_success
    paths:
      - dist/ses-website/
  only:
    - master

deploy:
  stage: "deploy"
  environment:
    name: production
  dependencies:
    - build
  script:
    - npm run deploy
  only:
    - master
