runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /
    static_files: dist/ses-website/index.html
    upload: dist/ses-website/index.html
    secure: always
  - url: /
    static_dir: dist/ses-website
    secure: always
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE